### ISSUE TITLE
Light and Dark card themes have no indication of card rarity 

### ISSUE THREAD

**Issue by tknights2015** [Epix37/HDT-Test#2]
Light and Dark card themes have no indication of card rarity. Minimal and classic do have this

**Comment by azeier** [comment]
A 2px line on the right seems to work quite nicely for colored frames (same for light)
![img](http://i.imgur.com/5DNjwbD.png). 

Maybe a bit lower opacity on those?

Not sure what to do about gems, if anything. Couldn't find anything that looks good. @andburn ideas?

**Comment by tknights2015** [comment]
Maybe a few  more px like the minimal?
![combined](https://cloud.githubusercontent.com/assets/16232528/14021255/6286486e-f1a0-11e5-84de-7d8855741415.jpg)

**Comment by azeier** [comment]
Working on redesigning the light/dark ones.

I don't like the colored bar on the right too much, maybe I'll be able to come up with something better.

**Comment by azeier** [comment]
I think these will be the final themes: http://imgur.com/a/326ZU

**Comment by tknights2015** [comment]
I think those are good. I like the designation on the casting cost background.

**Comment by tknights2015** [comment]
Love the changes. (Especially Frost) Light option still hard to see the rarity.
![light option](https://cloud.githubusercontent.com/assets/16232528/14054441/e208d562-f29e-11e5-9102-b03b2b5f7ba2.JPG)

**Comment by azeier** [comment]
The light/dark themes from pre1 wont be in the 13.18 release.

If you overwrote your installation with the PRE3, you still see it because you still have the `Images/Themes/Bars/light` folder form the PRE1 version.

**Comment by tknights2015** [comment]
Thought that might be the issue. Will leave the extra till the update comes out.

**Comment by tknights2015** [comment]
Lavender Frost  :-)
![lavender frost](https://cloud.githubusercontent.com/assets/16232528/14062438/3f2b6abe-f364-11e5-82ea-645876c711e8.JPG)

**Comment by azeier** [comment]
Neat! Not something I would include as a default, but interesting. The gems seem to not quite fit. I do like the fade however! Reminds me of cherry blossoms.

We will probably end up having some area to download user-made card themes, wont we? I'll look into making them a bit more customizable, like being able to change the font and positions, etc.

**Comment by tknights2015** [comment]
Gems fit, numbers are too big for the gems I think.  Just did those quickly. I think user made card themes would be fun.
