### ISSUE TITLE
Deck list not displayed correctly.

### ISSUE THREAD

**Issue by tknights2015** [Epix37/HDT-Test#3]
Deck list in game has additional cards not in deck list in HDT and is unreadable.
![display with deck list](https://cloud.githubusercontent.com/assets/16232528/14005069/e044be7e-f124-11e5-9fe6-653101b05527.jpg)

**Comment by tknights2015** [comment]
Log file.
[log_2332016-182943.txt](https://github.com/Epix37/HDT-Test/files/187072/log_2332016-182943.txt)

Appears that 2 decks combined in the display?

**Comment by azeier** [comment]
steps to reproduce this?

**Comment by tknights2015** [comment]
In this instance I had played games with Secret Paladin and deck was displaying correctly. In game I switched to a Mage deck and had the incorrect deck popup up. Choose the MAge deck for HDT and resulted in this combined list.  While in game went directly to HDT selected the correct deck again, restarted HDT also. Still did not show deck correctly. After the was over, restarted HDT and have had issue since.

**Comment by tknights2015** [comment]
Same issue again. Cards not in deck, shown in deck when loaded. Restarted HDt and still displayed this until the game was over.
![1](https://cloud.githubusercontent.com/assets/16232528/14096604/5f3e47c6-f527-11e5-94d8-5b69a05fa21c.JPG)
[log_2832016-204520.txt](https://github.com/Epix37/HDT-Test/files/192805/log_2832016-204520.txt)

**Comment by azeier** [comment]
I'm semi-confident I managed to fix this now! Try 18.5: https://github.com/Epix37/HDT-Test/releases/tag/v0.13.18.5

**Comment by azeier** [comment]
fixed with pre-release v0.13.19
