### ISSUE TITLE
Ranked Game not recorded v0.13.18.5

### ISSUE THREAD

**Issue by tknights2015** [Epix37/HDT-Test#4]
Last ranked game in this log not recorded.
![ranked gamed 3_29](https://cloud.githubusercontent.com/assets/16232528/14124999/17ea15cc-f5c6-11e5-8868-466ff990a844.JPG)
[log_2932016-154613.txt](https://github.com/Epix37/HDT-Test/files/194384/log_2932016-154613.txt)

Stats set to record all games except spectator.

**Comment by azeier** [comment]
Did you switch decks at the very end of the game?

**Comment by tknights2015** [comment]
No, I don't think I switched decks. When using the test versions do HDT I tend to check more often on the logging and recording.

**Comment by azeier** [comment]
From the log it looks like HDT reset at the very end of the match (not by auto detection though). Let me know if you see this again.

**Comment by tknights2015** [comment]
Will do.
