### ISSUE TITLE
v1.3.0-pre1 Crashes after deleting decks.

### ISSUE THREAD

**Issue by tknights2015** [Epix37/HDT-Test#5]
HDT crashes after deleting decks and then crashes on start up each time.

[Crash report 2952017-1359.txt](https://github.com/azeier/HDT-Test/files/1036585/Crash.report.2952017-1359.txt)

**Comment by azeier** [comment]
That has been fixed. You should be using the dev builds if anything: https://github.com/HearthSim/HDT-dev-builds/releases/latest

**Comment by tknights2015** [comment]
Hello,
Thank you. I was subscribed before to this email. Sorry, If I was using the wrong version.
 
Thanks
Tracy
